"""Link Stock and User Tables

Revision ID: 4566df78a868
Revises: 53749398d591
Create Date: 2020-03-12 22:38:43.705081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4566df78a868'
down_revision = '53749398d591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stocks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type='foreignkey')
    op.drop_column('stocks', 'user_id')
    # ### end Alembic commands ###
