"""Added authentication to users

Revision ID: 819538703899
Revises: abaf6f62b5f4
Create Date: 2020-03-01 08:28:29.276792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819538703899'
down_revision = 'abaf6f62b5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    # ### end Alembic commands ###
